'use client';

import React, { useState, useEffect } from 'react';
import { GlobalContainer } from '@/components/layout';
import { SectionHeading } from '@/components/ui';

// Convert key to Go field name (PascalCase)
function toGoFieldName(key: string): string {
  const parts = key.split(/[_\-\s.]+/).filter(Boolean);
  if (parts.length === 0) return 'Field';
  return parts.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('');
}

// Singularize for array item struct names
function singularize(word: string): string {
  if (word.endsWith('ies')) return word.slice(0, -3) + 'y';
  if (/(ses|xes|zes|ches|shes)$/.test(word)) return word.slice(0, -2);
  if (word.endsWith('s') && !word.endsWith('ss')) return word.slice(0, -1);
  return word;
}

function toGoStructName(nameHint: string): string {
  const parts = nameHint.split(/[_\-\s.]+/).filter(Boolean);
  if (parts.length === 0) return 'Generated';
  return parts.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('');
}

// Determine Go type
function getGoType(
  value: any,
  structs: Record<string, string>,
  nameHint: string
): string {
  if (value === null) return 'interface{}';

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]interface{}';
    const itemNameHint = singularize(nameHint);
    const types = Array.from(
      new Set(value.map((v) => getGoType(v, structs, itemNameHint)))
    );
    if (types.length === 1) return `[]${types[0]}`;
    return '[]interface{}';
  }

  if (typeof value === 'object') {
    const structName = toGoStructName(nameHint);
    const fields: string[] = [];
    for (const [k, v] of Object.entries(value)) {
      const fieldName = toGoFieldName(k);
      const fieldType = getGoType(v, structs, k);
      fields.push(`\t${fieldName} ${fieldType} \`json:"${k}"\``);
    }
    structs[structName] = `type ${structName} struct {\n${fields.join('\n')}\n}`;
    return structName;
  }

  if (typeof value === 'number') return Number.isInteger(value) ? 'int' : 'float64';
  if (typeof value === 'boolean') return 'bool';
  if (typeof value === 'string') return 'string';
  return 'interface{}';
}

function generateGoStruct(json: any): string {
  const structs: Record<string, string> = {};

  if (Array.isArray(json)) {
    if (json.length === 0) {
      return 'type AutoGenerated = []interface{}';
    }
    const itemType = getGoType(json[0], structs, 'AutoGeneratedItem');
    const structBlocks = Object.values(structs);
    return [...structBlocks, `type AutoGenerated = []${itemType}`].join('\n\n');
  }

  if (typeof json === 'object' && json !== null) {
    const fields: string[] = [];
    for (const [k, v] of Object.entries(json)) {
      const fieldName = toGoFieldName(k);
      const fieldType = getGoType(v, structs, k);
      fields.push(`\t${fieldName} ${fieldType} \`json:"${k}"\``);
    }
    const mainStruct = `type AutoGenerated struct {\n${fields.join('\n')}\n}`;
    const structBlocks = Object.values(structs);
    return [...structBlocks, mainStruct].join('\n\n');
  }

  return `type AutoGenerated = ${getGoType(json, structs, 'AutoGenerated')}`;
}

export default function JsonToGoPage() {
  const [jsonInput, setJsonInput] = useState(
    '{\n  "id": 101,\n  "name": "VelnoxLabs",\n  "active": true,\n  "tags": ["dev", "tools"]\n}'
  );
  const [goOutput, setGoOutput] = useState('');
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState('');
  const [feedback, setFeedback] = useState('');
  const [feedbackSent, setFeedbackSent] = useState(false);

  const handleConvert = (val: string) => {
    setError('');
    if (!val.trim()) {
      setGoOutput('');
      return;
    }
    try {
      const parsed = JSON.parse(val);
      setGoOutput(generateGoStruct(parsed));
    } catch (err: any) {
      setError('Invalid JSON syntax: ' + err.message);
      setGoOutput('');
    }
  };

  useEffect(() => {
    handleConvert(jsonInput);
  }, [jsonInput]);

  const handleCopy = () => {
    if (!goOutput) return;
    navigator.clipboard.writeText(goOutput);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleFeedbackSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!feedback.trim()) return;
    setFeedbackSent(true);
    setFeedback('');
    setTimeout(() => setFeedbackSent(false), 3000);
  };

  const schemaData = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'SoftwareApplication',
        'name': 'VelnoxLabs JSON to Go Struct Generator',
        'operatingSystem': 'All',
        'applicationCategory': 'DeveloperApplication',
        'offers': { '@type': 'Offer', 'price': '0', 'priceCurrency': 'USD' },
        'description': 'Convert JSON objects into Go struct definitions instantly with proper field names and json tags. Full support for nested objects, arrays, and nulls.'
      },
      {
        '@type': 'FAQPage',
        'mainEntity': [
          {
            '@type': 'Question',
            'name': 'How to generate Go struct from JSON?',
            'acceptedAnswer': { '@type': 'Answer', 'text': 'Paste your JSON and the tool instantly generates Go struct definitions with proper field names and json tags.' }
          },
          {
            '@type': 'Question',
            'name': 'Does it support nested objects and arrays?',
            'acceptedAnswer': { '@type': 'Answer', 'text': 'Yes, the generator recursively handles nested objects (creating separate named structs), arrays of primitives, and arrays of objects.' }
          }
        ]
      }
    ]
  };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schemaData) }} />

      <GlobalContainer maxWidth="2xl">
        <div style={{ paddingTop: 'var(--space-8)', paddingBottom: 'var(--space-16)' }}>
          <SectionHeading
            title="JSON to Go Struct Generator"
            subtitle="Convert JSON payloads into Go struct definitions instantly — nested objects and arrays supported."
          />

          {/* ========== TOOL UI ========== */}
          <div style={{ backgroundColor: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '12px', padding: '24px', marginTop: 'var(--space-6)' }}>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '20px' }}>
              <div>
                <label style={{ color: '#fff', fontSize: '0.875rem', fontWeight: 600, display: 'block', marginBottom: '8px' }}>JSON Input:</label>
                <textarea
                  value={jsonInput}
                  onChange={(e) => setJsonInput(e.target.value)}
                  rows={14}
                  placeholder="Paste JSON here..."
                  style={{ width: '100%', backgroundColor: 'rgba(0,0,0,0.3)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '8px', color: '#fff', padding: '12px', fontFamily: 'monospace', fontSize: '0.85rem', outline: 'none', resize: 'vertical' }}
                />
              </div>
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
                  <label style={{ color: '#fff', fontSize: '0.875rem', fontWeight: 600 }}>Go Struct Output:</label>
                  <button
                    onClick={handleCopy}
                    disabled={!goOutput}
                    style={{ backgroundColor: goOutput ? 'rgba(59, 130, 246, 0.15)' : 'rgba(255,255,255,0.05)', color: goOutput ? '#60a5fa' : '#64748b', border: '1px solid rgba(59, 130, 246, 0.3)', borderRadius: '6px', padding: '4px 12px', fontSize: '0.75rem', fontWeight: 600, cursor: goOutput ? 'pointer' : 'not-allowed' }}
                  >
                    {copied ? 'Copied!' : 'Copy Go'}
                  </button>
                </div>
                <textarea
                  value={goOutput}
                  readOnly
                  rows={14}
                  placeholder="Go struct will appear here..."
                  style={{ width: '100%', backgroundColor: 'rgba(0,0,0,0.3)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '8px', color: '#34d399', padding: '12px', fontFamily: 'monospace', fontSize: '0.85rem', outline: 'none', resize: 'vertical' }}
                />
              </div>
            </div>

            {error && (
              <div style={{ marginTop: '12px', backgroundColor: 'rgba(239, 68, 68, 0.1)', border: '1px solid rgba(239, 68, 68, 0.3)', borderRadius: '8px', padding: '12px' }}>
                <p style={{ color: '#f87171', fontSize: '0.85rem', margin: 0 }}>❌ {error}</p>
              </div>
            )}
          </div>

          {/* ========== SEO CONTENT ========== */}
          <div style={{ marginTop: '48px', backgroundColor: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '12px', padding: '32px' }}>
            <h2 style={{ fontSize: '1.5rem', fontWeight: 700, color: '#ffffff', marginBottom: '16px' }}>What is a JSON to Go Struct Generator?</h2>
            <p style={{ color: '#94a3b8', lineHeight: 1.7, marginBottom: '24px' }}>
              This tool converts JSON objects into Go struct definitions with proper field names and json tags. It saves backend Go developers from manually writing struct types for API responses. It supports deeply nested objects, arrays of primitives, arrays of objects, and null values.
            </p>

            <h3 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#ffffff', marginBottom: '12px', marginTop: '24px' }}>How to Use This Tool</h3>
            <ul style={{ color: '#94a3b8', lineHeight: 1.9, paddingLeft: '20px', marginBottom: '24px' }}>
              <li>Paste your JSON into the input box.</li>
              <li>The Go struct is generated instantly with proper field names and json tags.</li>
              <li>Nested objects generate separate named structs.</li>
              <li>Click <strong style={{ color: '#34d399' }}>Copy Go</strong> to copy the struct to your clipboard.</li>
            </ul>

            <h3 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#ffffff', marginBottom: '12px', marginTop: '24px' }}>Type Mappings</h3>
            <ul style={{ color: '#94a3b8', lineHeight: 1.9, paddingLeft: '20px', marginBottom: '24px' }}>
              <li><code style={{ color: '#60a5fa' }}>string</code> → <code style={{ color: '#34d399' }}>string</code></li>
              <li><code style={{ color: '#60a5fa' }}>integer</code> → <code style={{ color: '#34d399' }}>int</code></li>
              <li><code style={{ color: '#60a5fa' }}>float</code> → <code style={{ color: '#34d399' }}>float64</code></li>
              <li><code style={{ color: '#60a5fa' }}>boolean</code> → <code style={{ color: '#34d399' }}>bool</code></li>
              <li><code style={{ color: '#60a5fa' }}>null</code> → <code style={{ color: '#34d399' }}>interface{'{'}{'}'}</code></li>
              <li><code style={{ color: '#60a5fa' }}>array</code> → <code style={{ color: '#34d399' }}>[]Type</code></li>
              <li><code style={{ color: '#60a5fa' }}>nested object</code> → separate <code style={{ color: '#34d399' }}>struct</code></li>
            </ul>

            <h3 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#ffffff', marginBottom: '16px', marginTop: '24px' }}>Frequently Asked Questions</h3>

            <div style={{ marginBottom: '16px' }}>
              <h4 style={{ fontSize: '1rem', fontWeight: 600, color: '#60a5fa', marginBottom: '6px' }}>Does it support nested objects and arrays?</h4>
              <p style={{ color: '#94a3b8', lineHeight: 1.6 }}>Yes, the generator recursively handles deeply nested objects (creating separate named structs), arrays of primitives, and arrays of objects.</p>
            </div>

            <div style={{ marginBottom: '16px' }}>
              <h4 style={{ fontSize: '1rem', fontWeight: 600, color: '#60a5fa', marginBottom: '6px' }}>Is this tool free to use?</h4>
              <p style={{ color: '#94a3b8', lineHeight: 1.6 }}>Yes, VelnoxLabs JSON to Go Struct Generator is 100% free with no sign-up required.</p>
            </div>

            <div style={{ marginBottom: '16px' }}>
              <h4 style={{ fontSize: '1rem', fontWeight: 600, color: '#60a5fa', marginBottom: '6px' }}>Is my data secure?</h4>
              <p style={{ color: '#94a3b8', lineHeight: 1.6 }}>Absolutely. All processing happens entirely in your browser using client-side JavaScript. Your data never leaves your device.</p>
            </div>
          </div>

          {/* ========== FEEDBACK FORM ========== */}
          <div className="bg-slate-900/40 border border-slate-800 p-8 rounded-2xl mt-12">
            <h3 className="text-xl font-bold text-white mb-2">Got Feedback or Feature Requests?</h3>
            <p className="text-slate-400 mb-6 text-sm">Help us enhance VelnoxLabs developer utility standards. Share your feedback below!</p>
            <form onSubmit={handleFeedbackSubmit} className="space-y-4">
              <textarea
                rows={4}
                value={feedback}
                onChange={(e) => setFeedback(e.target.value)}
                placeholder="Write your suggestions or feature requests here..."
                className="w-full bg-slate-950 border border-slate-800 rounded-xl p-4 text-slate-200 focus:outline-none focus:border-slate-600 text-sm resize-none"
              ></textarea>
              <button type="submit" className="bg-emerald-600 hover:bg-emerald-500 text-white font-medium px-6 py-2.5 rounded-xl transition text-sm">
                {feedbackSent ? 'Sent!' : 'Submit Suggestion'}
              </button>
            </form>
          </div>

        </div>
      </GlobalContainer>
    </>
  );
}
