import { PresetUA } from '../types/useragent';

export const USER_AGENT_PRESETS: PresetUA[] = [
  // 1. Desktop Browsers
  {
    id: 'preset_chrome_win11',
    name: 'Google Chrome 128 on Windows 11',
    category: 'Desktop',
    ua: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36',
    description: 'Latest Google Chrome browser running on 64-bit Windows 11 desktop.',
    tags: ['Chrome', 'Windows', 'Blink', 'Desktop'],
  },
  {
    id: 'preset_safari_mac_m3',
    name: 'Apple Safari 17.5 on macOS Sonoma (Apple Silicon)',
    category: 'Desktop',
    ua: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15',
    description: 'Apple Safari 17.5 browser on macOS Sonoma desktop.',
    tags: ['Safari', 'macOS', 'WebKit', 'Apple Silicon'],
  },
  {
    id: 'preset_edge_win11',
    name: 'Microsoft Edge 128 on Windows 11',
    category: 'Desktop',
    ua: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0',
    description: 'Chromium-based Microsoft Edge browser on Windows 11.',
    tags: ['Edge', 'Windows', 'Microsoft', 'Blink'],
  },
  {
    id: 'preset_firefox_ubuntu',
    name: 'Mozilla Firefox 129 on Ubuntu Linux',
    category: 'Desktop',
    ua: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0',
    description: 'Gecko-based Firefox browser on Ubuntu 24.04 Linux x86_64.',
    tags: ['Firefox', 'Ubuntu', 'Linux', 'Gecko'],
  },
  {
    id: 'preset_arc_mac',
    name: 'Arc Browser 1.50 on macOS',
    category: 'Desktop',
    ua: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Arc/1.50.0',
    description: 'The Browser Company Arc browser running on macOS.',
    tags: ['Arc', 'macOS', 'Blink'],
  },
  {
    id: 'preset_brave_win',
    name: 'Brave Browser 1.68 on Windows 11',
    category: 'Desktop',
    ua: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Brave/1.68.128',
    description: 'Privacy-focused Brave browser on Windows 11.',
    tags: ['Brave', 'Privacy', 'Windows'],
  },

  // 2. Mobile & Tablet
  {
    id: 'preset_iphone15pro',
    name: 'iPhone 15 Pro (Safari / iOS 17.4)',
    category: 'Mobile & Tablet',
    ua: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Mobile/15E148 Safari/605.1.15',
    description: 'Apple iPhone 15 Pro mobile device on iOS 17.4.',
    tags: ['iPhone', 'iOS', 'Safari', 'Mobile'],
  },
  {
    id: 'preset_galaxy_s24',
    name: 'Samsung Galaxy S24 Ultra (Samsung Internet)',
    category: 'Mobile & Tablet',
    ua: 'Mozilla/5.0 (Linux; Android 14; SM-S928B) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/24.0 Chrome/120.0.6099.230 Mobile Safari/537.36',
    description: 'Samsung Galaxy S24 Ultra Android smartphone using Samsung Internet.',
    tags: ['Samsung', 'Android', 'Mobile'],
  },
  {
    id: 'preset_ipad_air',
    name: 'iPad Air M2 (iPadOS 17.4)',
    category: 'Mobile & Tablet',
    ua: 'Mozilla/5.0 (iPad; CPU OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Mobile/15E148 Safari/605.1.15',
    description: 'Apple iPad Air tablet on iPadOS 17.4.',
    tags: ['iPad', 'iPadOS', 'Tablet'],
  },
  {
    id: 'preset_pixel8pro',
    name: 'Google Pixel 8 Pro (Chrome / Android 14)',
    category: 'Mobile & Tablet',
    ua: 'Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.88 Mobile Safari/537.36',
    description: 'Google Pixel 8 Pro flagship smartphone on Android 14.',
    tags: ['Pixel', 'Android', 'Chrome', 'Mobile'],
  },

  // 3. AI Bots & Scrapers
  {
    id: 'preset_gptbot',
    name: 'GPTBot 1.0 (OpenAI AI Web Crawler)',
    category: 'AI Bots & Scrapers',
    ua: 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; GPTBot/1.0; +https://openai.com/gptbot)',
    description: 'OpenAI official web crawler used to fetch web content for GPT models.',
    tags: ['OpenAI', 'GPTBot', 'AI Crawler', 'Bot'],
  },
  {
    id: 'preset_chatgpt_user',
    name: 'ChatGPT-User Web Browsing Plugin',
    category: 'AI Bots & Scrapers',
    ua: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 ChatGPT-User/1.0',
    description: 'Triggered when a ChatGPT user asks ChatGPT to browse a web page.',
    tags: ['ChatGPT', 'OpenAI', 'AI Scraper'],
  },
  {
    id: 'preset_claudebot',
    name: 'ClaudeBot (Anthropic AI Web Scraper)',
    category: 'AI Bots & Scrapers',
    ua: 'Mozilla/5.0 (compatible; ClaudeBot/1.0; +https://anthropic.com/claudebot)',
    description: 'Anthropic AI crawler for indexing web content for Claude models.',
    tags: ['Anthropic', 'Claude', 'AI Crawler'],
  },
  {
    id: 'preset_perplexitybot',
    name: 'PerplexityBot (Perplexity AI Search Crawler)',
    category: 'AI Bots & Scrapers',
    ua: 'Mozilla/5.0 (compatible; PerplexityBot/1.0; +https://perplexity.ai/bot)',
    description: 'Real-time web retrieval bot for Perplexity AI search engine.',
    tags: ['Perplexity', 'AI Search', 'Bot'],
  },
  {
    id: 'preset_bytespider',
    name: 'Bytespider (ByteDance AI Scraper)',
    category: 'AI Bots & Scrapers',
    ua: 'Mozilla/5.0 (compatible; Bytespider; spider-feedback@bytedance.com)',
    description: 'ByteDance AI and TikTok web scraping crawler.',
    tags: ['ByteDance', 'TikTok', 'AI Bot'],
  },

  // 4. Search Engine Crawlers
  {
    id: 'preset_googlebot_desktop',
    name: 'Googlebot Desktop (Google Search Crawler)',
    category: 'Search Engine Crawlers',
    ua: 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
    description: 'Primary Google search engine indexing bot for desktop pages.',
    tags: ['Google', 'Googlebot', 'SEO', 'Search Crawler'],
  },
  {
    id: 'preset_bingbot',
    name: 'Bingbot (Microsoft Bing Crawler)',
    category: 'Search Engine Crawlers',
    ua: 'Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
    description: 'Microsoft Bing search engine web crawler.',
    tags: ['Bing', 'Microsoft', 'SEO'],
  },
  {
    id: 'preset_yandexbot',
    name: 'YandexBot (Yandex Search)',
    category: 'Search Engine Crawlers',
    ua: 'Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)',
    description: 'Yandex search engine crawler.',
    tags: ['Yandex', 'Search Bot'],
  },
  {
    id: 'preset_applebot',
    name: 'Applebot (Apple Search / Siri)',
    category: 'Search Engine Crawlers',
    ua: 'Mozilla/5.0 (Device; Applebot/0.1; +http://www.apple.com/go/applebot)',
    description: 'Apple web crawler for Apple Maps, Spotlight, and Siri search.',
    tags: ['Apple', 'Siri', 'Search Bot'],
  },

  // 5. Gaming & Smart TV
  {
    id: 'preset_ps5',
    name: 'PlayStation 5 Console Browser',
    category: 'Gaming & Smart TV',
    ua: 'Mozilla/5.0 (PlayStation 5 7.00) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15',
    description: 'Built-in browser for Sony PlayStation 5 console.',
    tags: ['PlayStation', 'PS5', 'Console', 'Sony'],
  },
  {
    id: 'preset_steamdeck',
    name: 'Steam Deck (SteamOS / Valve)',
    category: 'Gaming & Smart TV',
    ua: 'Mozilla/5.0 (X11; SteamDeck; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    description: 'Handheld Valve Steam Deck running SteamOS Linux.',
    tags: ['Steam Deck', 'Valve', 'Gaming', 'Linux'],
  },
  {
    id: 'preset_lg_webos_tv',
    name: 'LG webOS Smart TV',
    category: 'Gaming & Smart TV',
    ua: 'Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.215 Safari/537.36 WebAppManager',
    description: 'LG Smart TV running webOS OS.',
    tags: ['LG', 'webOS', 'Smart TV'],
  },

  // 6. Legacy & Rare
  {
    id: 'preset_ie11',
    name: 'Internet Explorer 11 on Windows 7',
    category: 'Legacy & Rare',
    ua: 'Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko',
    description: 'Legacy Microsoft Internet Explorer 11 browser.',
    tags: ['IE11', 'Trident', 'Legacy'],
  },
  {
    id: 'preset_netscape4',
    name: 'Netscape Navigator 4.7 (Historical 1999)',
    category: 'Legacy & Rare',
    ua: 'Mozilla/4.7 [en] (Win98; I)',
    description: 'Historical Netscape Communicator 4.7 browser from 1999.',
    tags: ['Netscape', 'Historical', 'Retro'],
  },
  {
    id: 'preset_curl',
    name: 'cURL Command Line Utility',
    category: 'Legacy & Rare',
    ua: 'curl/8.4.0',
    description: 'cURL HTTP command line client utility.',
    tags: ['cURL', 'CLI', 'Tool'],
  },
];