'use client';

import React, { useState, useEffect } from 'react';
import { GlobalContainer } from '@/components/layout';
import { SectionHeading } from '@/components/ui';

// Convert value to TS type string
function getTsType(value: any, interfaces: Record<string, string>, nameHint: string): string {
  if (value === null) return 'null';

  if (Array.isArray(value)) {
    if (value.length === 0) return 'any[]';
    const types = Array.from(new Set(value.map((v) => getTsType(v, interfaces, nameHint + 'Item'))));
    if (types.length === 1) return `${types[0]}[]`;
    return `(${types.join(' | ')})[]`;
  }

  if (typeof value === 'object') {
    const interfaceName = capitalize(nameHint);
    const lines: string[] = [];
    for (const [k, v] of Object.entries(value)) {
      lines.push(`  ${k}: ${getTsType(v, interfaces, k)};`);
    }
    interfaces[interfaceName] = `interface ${interfaceName} {\n${lines.join('\n')}\n}`;
    return interfaceName;
  }

  if (typeof value === 'number') return 'number';
  if (typeof value === 'boolean') return 'boolean';
  if (typeof value === 'string') return 'string';
  return 'any';
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function generateInterfaces(json: any): string {
  if (Array.isArray(json)) {
    // Root is array
    if (json.length === 0) return 'type AutoGenerated = any[];';
    const interfaces: Record<string, string> = {};
    // ✅ FIX: Use 'AutoGeneratedItem' as nameHint to avoid conflict with 'AutoGenerated' type
    const itemType = getTsType(json[0], interfaces, 'AutoGeneratedItem');
    let output = '';
    Object.values(interfaces).forEach((i) => (output += i + '\n\n'));
    output += `type AutoGenerated = ${itemType}[];`;
    return output;
  }

  if (typeof json === 'object' && json !== null) {
    const interfaces: Record<string, string> = {};
    const lines: string[] = [];
    for (const [k, v] of Object.entries(json)) {
      lines.push(`  ${k}: ${getTsType(v, interfaces, k)};`);
    }
    let output = '';
    Object.values(interfaces).forEach((i) => (output += i + '\n\n'));
    output += `interface AutoGenerated {\n${lines.join('\n')}\n}`;
    return output;
  }

  return `type AutoGenerated = ${getTsType(json, {}, 'AutoGenerated')};`;
}

export default function JsonToTsPage() {
  const [jsonInput, setJsonInput] = useState(
    '{\n  "id": "uuid-123",\n  "score": 98.5,\n  "roles": ["admin", "user"]\n}'
  );
  const [tsOutput, setTsOutput] = useState('');
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState('');
  const [feedback, setFeedback] = useState('');
  const [feedbackSent, setFeedbackSent] = useState(false);

  const handleConvert = (val: string) => {
    setError('');
    if (!val.trim()) {
      setTsOutput('');
      return;
    }
    try {
      const parsed = JSON.parse(val);
      setTsOutput(generateInterfaces(parsed));
    } catch (err: any) {
      setError('Invalid JSON syntax: ' + err.message);
      setTsOutput('');
    }
  };

  useEffect(() => {
    handleConvert(jsonInput);
  }, [jsonInput]);

  const handleCopy = () => {
    if (!tsOutput) return;
    navigator.clipboard.writeText(tsOutput);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleFeedbackSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!feedback.trim()) return;
    setFeedbackSent(true);
    setFeedback('');
    setTimeout(() => setFeedbackSent(false), 3000);
  };

  const schemaData = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'SoftwareApplication',
        'name': 'VelnoxLabs JSON to TypeScript Interface Generator',
        'operatingSystem': 'All',
        'applicationCategory': 'DeveloperApplication',
        'offers': { '@type': 'Offer', 'price': '0', 'priceCurrency': 'USD' },
        'description': 'Convert JSON objects into typed TypeScript interfaces instantly with support for nested objects, arrays, unions, and nulls.'
      },
      {
        '@type': 'FAQPage',
        'mainEntity': [
          {
            '@type': 'Question',
            'name': 'How to generate TypeScript interface from JSON?',
            'acceptedAnswer': { '@type': 'Answer', 'text': 'Paste your JSON and the tool instantly generates a TypeScript interface with proper typing including nested objects and arrays.' }
          },
          {
            '@type': 'Question',
            'name': 'Does it support nested objects and arrays?',
            'acceptedAnswer': { '@type': 'Answer', 'text': 'Yes, it recursively handles nested objects, arrays of primitives, arrays of objects, and mixed-type unions.' }
          }
        ]
      }
    ]
  };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schemaData) }} />

      <GlobalContainer maxWidth="2xl">
        <div style={{ paddingTop: 'var(--space-8)', paddingBottom: 'var(--space-16)' }}>
          <SectionHeading
            title="JSON to TypeScript Interface"
            subtitle="Convert JSON objects into typed TypeScript interfaces instantly — nested objects and arrays supported."
          />

          {/* ========== TOOL UI ========== */}
          <div style={{ backgroundColor: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '12px', padding: '24px', marginTop: 'var(--space-6)' }}>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '20px' }}>
              <div>
                <label style={{ color: '#fff', fontSize: '0.875rem', fontWeight: 600, display: 'block', marginBottom: '8px' }}>JSON Input:</label>
                <textarea
                  value={jsonInput}
                  onChange={(e) => setJsonInput(e.target.value)}
                  rows={14}
                  placeholder="Paste JSON here..."
                  style={{ width: '100%', backgroundColor: 'rgba(0,0,0,0.3)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '8px', color: '#fff', padding: '12px', fontFamily: 'monospace', fontSize: '0.85rem', outline: 'none', resize: 'vertical' }}
                />
              </div>
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
                  <label style={{ color: '#fff', fontSize: '0.875rem', fontWeight: 600 }}>TypeScript Interface Output:</label>
                  <button
                    onClick={handleCopy}
                    disabled={!tsOutput}
                    style={{ backgroundColor: tsOutput ? 'rgba(59, 130, 246, 0.15)' : 'rgba(255,255,255,0.05)', color: tsOutput ? '#60a5fa' : '#64748b', border: '1px solid rgba(59, 130, 246, 0.3)', borderRadius: '6px', padding: '4px 12px', fontSize: '0.75rem', fontWeight: 600, cursor: tsOutput ? 'pointer' : 'not-allowed' }}
                  >
                    {copied ? 'Copied!' : 'Copy TS'}
                  </button>
                </div>
                <textarea
                  value={tsOutput}
                  readOnly
                  rows={14}
                  placeholder="TypeScript interface will appear here..."
                  style={{ width: '100%', backgroundColor: 'rgba(0,0,0,0.3)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '8px', color: '#34d399', padding: '12px', fontFamily: 'monospace', fontSize: '0.85rem', outline: 'none', resize: 'vertical' }}
                />
              </div>
            </div>

            {error && (
              <div style={{ marginTop: '12px', backgroundColor: 'rgba(239, 68, 68, 0.1)', border: '1px solid rgba(239, 68, 68, 0.3)', borderRadius: '8px', padding: '12px' }}>
                <p style={{ color: '#f87171', fontSize: '0.85rem', margin: 0 }}>❌ {error}</p>
              </div>
            )}
          </div>

          {/* ========== SEO CONTENT ========== */}
          <div style={{ marginTop: '48px', backgroundColor: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '12px', padding: '32px' }}>
            <h2 style={{ fontSize: '1.5rem', fontWeight: 700, color: '#ffffff', marginBottom: '16px' }}>What is a JSON to TypeScript Interface Generator?</h2>
            <p style={{ color: '#94a3b8', lineHeight: 1.7, marginBottom: '24px' }}>
              This tool converts JSON objects into TypeScript interfaces with proper typing. Front-end developers use it to quickly add types to API responses in React, Vue, and Angular applications. It supports deeply nested objects, arrays of primitives, arrays of objects, null values, and mixed-type unions.
            </p>

            <h3 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#ffffff', marginBottom: '12px', marginTop: '24px' }}>How to Use This Tool</h3>
            <ul style={{ color: '#94a3b8', lineHeight: 1.9, paddingLeft: '20px', marginBottom: '24px' }}>
              <li>Paste your JSON into the input box.</li>
              <li>The TypeScript interface is generated instantly with proper types.</li>
              <li>Nested objects generate separate named interfaces.</li>
              <li>Click <strong style={{ color: '#34d399' }}>Copy TS</strong> to copy the interface to your clipboard.</li>
            </ul>

            <h3 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#ffffff', marginBottom: '12px', marginTop: '24px' }}>Type Mappings</h3>
            <ul style={{ color: '#94a3b8', lineHeight: 1.9, paddingLeft: '20px', marginBottom: '24px' }}>
              <li><code style={{ color: '#60a5fa' }}>string</code> → <code style={{ color: '#34d399' }}>string</code></li>
              <li><code style={{ color: '#60a5fa' }}>number</code> → <code style={{ color: '#34d399' }}>number</code></li>
              <li><code style={{ color: '#60a5fa' }}>boolean</code> → <code style={{ color: '#34d399' }}>boolean</code></li>
              <li><code style={{ color: '#60a5fa' }}>null</code> → <code style={{ color: '#34d399' }}>null</code></li>
              <li><code style={{ color: '#60a5fa' }}>array</code> → <code style={{ color: '#34d399' }}>Type[]</code> or <code style={{ color: '#34d399' }}>(A | B)[]</code></li>
              <li><code style={{ color: '#60a5fa' }}>nested object</code> → separate <code style={{ color: '#34d399' }}>interface</code></li>
            </ul>

            <h3 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#ffffff', marginBottom: '16px', marginTop: '24px' }}>Frequently Asked Questions</h3>

            <div style={{ marginBottom: '16px' }}>
              <h4 style={{ fontSize: '1rem', fontWeight: 600, color: '#60a5fa', marginBottom: '6px' }}>Does it support nested objects and arrays?</h4>
              <p style={{ color: '#94a3b8', lineHeight: 1.6 }}>Yes, the generator recursively handles deeply nested objects (creating separate named interfaces) and arrays of primitives, arrays of objects, and mixed-type unions.</p>
            </div>

            <div style={{ marginBottom: '16px' }}>
              <h4 style={{ fontSize: '1rem', fontWeight: 600, color: '#60a5fa', marginBottom: '6px' }}>Is this tool free to use?</h4>
              <p style={{ color: '#94a3b8', lineHeight: 1.6 }}>Yes, VelnoxLabs JSON to TypeScript Interface Generator is 100% free with no sign-up required.</p>
            </div>

            <div style={{ marginBottom: '16px' }}>
              <h4 style={{ fontSize: '1rem', fontWeight: 600, color: '#60a5fa', marginBottom: '6px' }}>Is my data secure?</h4>
              <p style={{ color: '#94a3b8', lineHeight: 1.6 }}>Absolutely. All processing happens entirely in your browser using client-side JavaScript. Your data never leaves your device.</p>
            </div>
          </div>

          {/* ========== FEEDBACK FORM ========== */}
          <div className="bg-slate-900/40 border border-slate-800 p-8 rounded-2xl mt-12">
            <h3 className="text-xl font-bold text-white mb-2">Got Feedback or Feature Requests?</h3>
            <p className="text-slate-400 mb-6 text-sm">Help us enhance VelnoxLabs developer utility standards. Share your feedback below!</p>
            <form onSubmit={handleFeedbackSubmit} className="space-y-4">
              <textarea
                rows={4}
                value={feedback}
                onChange={(e) => setFeedback(e.target.value)}
                placeholder="Write your suggestions or feature requests here..."
                className="w-full bg-slate-950 border border-slate-800 rounded-xl p-4 text-slate-200 focus:outline-none focus:border-slate-600 text-sm resize-none"
              ></textarea>
              <button type="submit" className="bg-emerald-600 hover:bg-emerald-500 text-white font-medium px-6 py-2.5 rounded-xl transition text-sm">
                {feedbackSent ? 'Sent!' : 'Submit Suggestion'}
              </button>
            </form>
          </div>

        </div>
      </GlobalContainer>
    </>
  );
}